# Site settings
title: Faacets Beta2 Documentation
email: info@faacets.com
description: > # this means to ignore newlines until "baseurl:"
  This page gathers the documentation about the faacets.com website and related software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.faacets.com" # the base hostname & protocol for your site
twitter_username: faacets
github_username:  faacets

# Build settings
markdown: kramdown
